# Use official Node.js image
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy package.json first (for caching)
COPY package*.json ./

# Install all dependencies
RUN npm install --only=production
# Copy the rest of your app
COPY . .

# Expose port
EXPOSE 3000

# Default command: production
CMD ["npm", "start"]
