
version: "3.9"

services:
  app:
    container_name: next-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:              
      - .env.local
    environment:
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:3000
    command: npm run dev

